### ISSUE TITLE
Unpin numkong on macOS once upstream ships 7.7.1+ wheels

### ISSUE THREAD

**Issue by shcheklein** [iterative/datachain#1874]
### Description

CI on macOS is currently broken for every PR: `numkong` 7.7.1 (transitive dep: `datachain[tests]` → `usearch` → `numkong`) was published to PyPI on 2026-07-21 as **sdist-only** — the upstream wheel pipeline failed mid-release ([Release Python run](https://github.com/ashvardanian/NumKong/actions/workflows/release-python.yml), v7.7.1: macOS and Linux wheel jobs failed, only the sdist was uploaded). The sdist requires OpenMP and Apple clang has no `omp.h`, so dependency install fails before any test runs:

```
python/distance.c:17:10: fatal error: 'omp.h' file not found
nox > Session tests-3.10 failed.
```

Example failing runs (from #1860, unrelated to its changes): [macos 3.10](https://github.com/datachain-ai/datachain/actions/runs/29873356872/job/88778612605), [macos 3.14](https://github.com/datachain-ai/datachain/actions/runs/29873356872/job/88778612580). Linux/Windows survive because their toolchains can build the sdist.

### Interim measure

`numkong!=7.7.1 ; sys_platform == 'darwin'` added to the `vector` extra (alongside `usearch`, which declares unbounded `numkong`) — resolves to 7.7.0, which shipped 14 macOS wheels. This also covers macOS users installing `datachain[vector]`, not just CI.

### This issue: remove the pin

NumKong ships full wheel matrices regularly (7.7.0: 99 files) and fixed a similar publishing problem within days ([ashvardanian/NumKong#359](https://github.com/ashvardanian/NumKong/issues/359), "7.7.0 is not on PYPI"), so this should be short-lived. Unpin when either:

- macOS wheels appear for 7.7.1 (`https://pypi.org/pypi/numkong/7.7.1/json` — currently 1 file), or
- a fixed 7.7.2+ is released with wheels (then the `!=7.7.1` exclusion becomes dead weight and should still be dropped for cleanliness).
