### ISSUE TITLE
`ArrowGenerator` is broken on caching with latest fsspec release

### ISSUE THREAD

**Issue by skshetry** [iterative/datachain#806]
### Description

Broken by https://github.com/fsspec/filesystem_spec/pull/1755.

```pytb
Traceback (most recent call last):]
  File "/Users/user/work/iterative/datachain/src/datachain/lib/arrow.py", line 90, in iter_records
    for record_batch in ds.to_batches(**kw):
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'closed'
/Users/user/work/iterative/datachain/src/datachain/lib/arrow.py:90: RuntimeWarning: coroutine 'AbstractFileSystem.open' was never awaited
  for record_batch in ds.to_batches(**kw):
```

Thanks to @dreadatour for catching the bug.

### Version Info

```Text

```

**Comment by shcheklein** [comment]
@skshetry it seems like a major issue, what it the solution for this? should we for now pin the previous version?
