### ISSUE TITLE
Unparameterized sequence annotations pass validation but fail in the SQL layer

### ISSUE THREAD

**Issue by shcheklein** [iterative/datachain#1923]
Unparameterized sequence annotations survive validation and then fail in the SQL layer. Bare `dict` is unaffected, so this is specific to sequences.

## Two independent entry points

**Root output**, which `is_chain_type` does gate:

```python
import datachain as dc

dc.read_values(x=[1]).map(y=lambda x: [x], output=list).to_values("y")
```

```
TypeError: ARRAY.__init__() missing 1 required positional argument: 'item_type'
```

**Model fields**, which never consult `is_chain_type` at all:

```python
import typing
import datachain as dc

class M(dc.DataModel):
    items: typing.List      # or list, Sequence, Iterable, Tuple

dc.read_values(m=[M(items=[1, 2])]).to_values("m.items")
```

Measured for every bare spelling:

| field annotation | failure |
|---|---|
| `list` | `TypeError: ARRAY.__init__() missing 1 required positional argument: 'item_type'` |
| `typing.List` | `IndexError: tuple index out of range` |
| `typing.Sequence` | `IndexError: tuple index out of range` |
| `typing.Iterable` | `IndexError: tuple index out of range` |
| `typing.Tuple` | `IndexError: tuple index out of range` |
| `dict` (control) | **OK** — `[{'k': 1}]` |

## Why

`python_to_sql(list)` returns the `Array` **class** rather than an instance, since there is no item type to parameterize it with; instantiation fails later. The abstract and `typing` spellings instead reach `_list_to_array`, which indexes `get_args(...)[0]` unconditionally — hence `IndexError`. `dict` maps to `JSON`, which takes no parameter, so it round-trips.

## Resolution must cover both paths

Rejecting unparameterized sequences in `is_chain_type` fixes the `output=` route only. Model fields bypass that check entirely, so a complete fix needs either:

- validation of model field annotations at schema-build time, or
- a safe rejection inside the converter (`python_to_sql` / `_list_to_array`) raising a clear, named error instead of `TypeError`/`IndexError`.

The converter-level guard is the one that closes both paths on its own.

Related: #1911 tightened arity handling for the parameterized forms; this is the zero-argument case that slipped through.

Pre-existing; not introduced by #1867 or #1911. Found while writing tests for #1915, which deliberately does not assert bare `list` as supported.

🤖 AI-assisted (Claude Code) — verify before relying on it.

**Comment by shcheklein** [comment]
Consolidated into #1942, which collects every case where an annotation passes validation and the storage layer cannot honour it.

This one is the unparameterized-sequence row, including that model fields bypass `is_chain_type` entirely.

Closing here so the work is tracked in one place. Nothing is dropped: the case is listed in #1942's table, and #1942 records that the list is probably incomplete and that the real fix is a round-trip property test rather than another round of individual patches.
